version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: novoinscricoespos
      POSTGRES_USER: pos 
      POSTGRES_PASSWORD: estudos 

  # Application Service
  app:
    container_name: inscricoespos
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db 
    environment:
      PGADMIN_DEFAULT_EMAIL: jota@jota.com
      PGADMIN_DEFAULT_PASSWORD: estudos 

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
